#pragma once

#define LIBOSMO_MSLOOKUP_VERSION UNKNOWN
#define LIBOSMO_MSLOOKUP_VERSION_STR "UNKNOWN"

#define LIBOSMO_MSLOOKUP_VERSION_MAJOR UNKNOWN
#define LIBOSMO_MSLOOKUP_VERSION_MINOR UNKNOWN
#define LIBOSMO_MSLOOKUP_VERSION_PATCH UNKNOWN

#define LIBOSMO_MSLOOKUP_VERSION_GREATER_EQUAL(major, minor, patch) \
	(LIBOSMO_MSLOOKUP_VERSION_MAJOR > (major) || \
	 (LIBOSMO_MSLOOKUP_VERSION_MAJOR == (major) && \
	  LIBOSMO_MSLOOKUP_VERSION_MINOR > (minor)) || \
	 (LIBOSMO_MSLOOKUP_VERSION_MAJOR == (major) && \
	  LIBOSMO_MSLOOKUP_VERSION_MINOR == (minor) && \
	  LIBOSMO_MSLOOKUP_VERSION_PATCH >= (patch)))
